version: '2.2'
services:
  rabbit:
    image: "rabbitmq"
    ports:
     - "5680:5672"  
  producer:
    build:
      context: .
      dockerfile: producerDockerfile
    restart: always
    depends_on:
     - rabbit
  consumer:
    build:
      context: .
      dockerfile: consumerDockerfile
    restart: always
    depends_on:
     - rabbit
